### ISSUE TITLE
Wrong time stamp in preprocessing?

### ISSUE THREAD

**Issue by halvgaard** [nklingen/Transformer-Time-Series-Forecasting#2]
Stumbled upon these identical lines in your preprocessing:
https://github.com/nklingen/Transformer-Time-Series-Forecasting/blob/d85a5fff2af508d3f3a7b64994d28dbe90818597/Preprocessing.py#L50-L51

I assume they should have .day and .month instead of .hour ?

**Comment by nklingen** [comment]
Hi Rasmus,

Thanks for reading my code and article, and for your feedback !

Absolutely, you caught a bug I oversaw. I am curious to run it again with the true day and month encodings, and see if the model can catch temporal dependencies over longer time periods. 

As to your other comment, I can unfortunately not added a runnable example at the moment, as the dataset is covered by an NDA with the company who provided the data. I have reached out to them to ask if they can provide a cleaned dataset that I could post for you. But to answer your questions, I am using a uni-variate time series. The preprocessing strips all other variables so that the model only takes humidity and the timestamp. In the transformer, this gives a dimension of 7 (humidity + 6 encodings for the timestamp).

In the full research project, I also tried multi-variate inputs but this didn’t improve the model, and I omitted it in the medium article.
Please let me know if you have another other questions or comments about my work :)

Best regards,
Natasha

**Comment by natashaklingenbrunn** [comment]
Hi Rasmus,

Absolutely, you caught a bug I oversaw. I have updated the code and am curious to run it again with the day and month encodings, and see if the model can catch temporal dependencies over longer time periods.

Thanks for the feedback !
